spring.application.name=slice-lending-api

spring.datasource.url=jdbc:postgresql://localhost:5432/slice_lending
spring.datasource.username=slice_app
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
