spring.application.name=slice-lending-api

spring.datasource.url=jdbc:postgresql://localhost:5432/slice_lending
spring.datasource.username=slice_app
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true


spring.mail.host=localhost
spring.mail.port=1025

spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.email-verification.base-url=http://localhost:8080/api/v1/auth/verify-email
app.mail.from=no-reply@slicelending.local