CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    account_status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),



    CONSTRAINT ck_users_role CHECK (
        role IN (
            'CUSTOMER',
            'LOAN_OFFICER',
            'UNDERWRITER',
            'OPERATIONS',
            'ADMIN',
            'AUDITOR'
        )
    ),

    CONSTRAINT ck_users_account_status CHECK (
        account_status IN (
            'PENDING_VERIFICATION',
            'ACTIVE',
            'LOCKED',
            'DISABLED'
        )
    )
);

CREATE TABLE customer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_customer_profiles PRIMARY KEY (id),

    CONSTRAINT uk_customer_profiles_user_id
        UNIQUE (user_id),

    CONSTRAINT fk_customer_profiles_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);