CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_email_verification_tokens
        PRIMARY KEY (id),

    CONSTRAINT uk_email_verification_tokens_token_hash
        UNIQUE (token_hash),

    CONSTRAINT fk_email_verification_tokens_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);

CREATE INDEX idx_email_verification_tokens_user_id
    ON email_verification_tokens(user_id);