CREATE TABLE loan_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_number VARCHAR(36) NOT NULL,
    customer_profile_id BIGINT NOT NULL,
    requested_amount NUMERIC(19,2) NOT NULL,
    loan_purpose VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,


    CONSTRAINT pk_loan_applications
    PRIMARY KEY (id),

    CONSTRAINT uk_loan_applications_application_number
    UNIQUE (application_number),

    CONSTRAINT fk_loan_applications_customer_profile_id
    FOREIGN KEY (customer_profile_id)
    REFERENCES customer_profiles(id),

    CONSTRAINT ck_loan_applications_requested_amount
        CHECK(requested_amount BETWEEN 1000.00 AND 100000.00),

    CONSTRAINT ck_loan_applications_loan_purpose
        CHECK(loan_purpose IN ('DEBT_CONSOLIDATION',
                              'HOME_IMPROVEMENT',
                              'MEDICAL_EXPENSES',
                              'AUTO',
                              'EDUCATION',
                              'MAJOR_PURCHASE',
                              'OTHER')),

    CONSTRAINT ck_loan_applications_status
        CHECK(status IN ('DRAFT'))
);

CREATE INDEX idx_loan_applications_customer_profile_id
ON loan_applications(customer_profile_id);

CREATE UNIQUE INDEX uk_loan_applications_one_draft_per_customer
ON loan_applications(customer_profile_id)
WHERE status = 'DRAFT';